### ISSUE TITLE
404 redirects to file name if path changes

### ISSUE THREAD

**Issue by mattgreg** [ockam-network/website#317]
As we build out our /learn pages we will probably continue to change folder structure as we have more documentation. This breaks existing URLs out in internet-land.

If there is a 404, we could check the file name for a match and then direct to that page. We can assume that the file names won't change. 

However if the file name changes, then assume the default behavior with a redirect to the home page.

**Comment by miedziak** [comment]
@mattgreg I make I quick research about possibilities and I think the more optimum way to solve this will be to use this plugin:
https://www.gatsbyjs.com/plugins/gatsby-redirect-from/#usage

So all you would have to do is to add `redirect_from` in your markdown files, where you will put an older path for this URL. Based on that we should get a nice server-side redirect. 

It's not SEO perfect ( since it's not HTTP 301 redirect ) but to achieve that, we would have probably make some entries in azure/cloudfront ( don't remember where we handle old URL redirects ). Keep it on the azure/cloudfront isn't also perfect since it won't be so clean and easy to manage.

**Comment by mattgreg** [comment]
That looks like a great solution, even if a little mechanical.

**Comment by miedziak** [comment]
@mattgreg I've added the plugin I've mentioned above. To handle normal pages ( not generated from MD files ) I have added different solutions. You can do this by adding an entry in the `redirect.csv` file. Check details in README in the pull request.

**Comment by mattgreg** [comment]
@miedziak 

can you add these instructions to the readme?

is `redirect_from` part of the header in the markdown pages - if so what's the syntax on that line. Can you create an example in the readme? We have a section in the readme for `markdown files metadata fields`

For the `redirect.csv` where should this file live? in the repo root?
