### ISSUE TITLE
Code of "Get Started: Secure Channel with Entity" leads to compile errors

### ISSUE THREAD

**Issue by cakebaker** [ockam-network/website#473]
If I take the code from [Secure Channel with Entity](https://www.ockam.io/learn/how-to-guides/rust/10-secure-channel-with-entity), I get some compile errors. For example, `IdentifierTrustPolicy` should be `TrustIdentifierPolicy`. I found a working version of the code in the ockam repository: https://github.com/ockam-network/ockam/blob/develop/examples/rust/get_started/examples/old/13-secure-channel-with-entity.rs. But I don't know if that code is still up-to-date, as it is in an `old` folder.

**Comment by mrinalwadhwa** [comment]
@cakebaker thank you for filing an issue 🙏 

[This example](https://github.com/ockam-network/ockam/blob/develop/examples/rust/get_started/examples/old/13-secure-channel-with-entity.rs) that uses `TrustIdentifierPolicy` is correct. It's in the old folder because we're releasing a brand new set of examples this weekend and are moving things around because of that.

**Comment by cakebaker** [comment]
Closing ticket as the new examples are online.

**Comment by mrinalwadhwa** [comment]
Thank @cakebaker 🙏 we'll post some more examples through the course of this week
